# [START runtime]
runtime: nodejs
vm: true
# [END runtime]    
threadsafe: yes
    
# Temporary setting to keep gcloud from uploading node_modules
skip_files:
- ^node_modules$
    
handlers:
- url: /.*
  script: index.js
  secure: always
